### PR TITLE
CONTRIB-7264: Add option to exclude inactive users' responses

### PR DESCRIPTION
**Pull request by tonyjbutler**
This commit adds the option to exclude inactive users' responses from questionnaire reports, in line with an increasing number of core Moodle activity modules.

### CODE REVIEW

**Comment by mchurchward** [comment]
Thanks for the contribution, but I am not familiar with excluding inactive user's responses in core. Can you refer me to the core modules that are doing this for comparison?

**Comment by tonyjbutler** [comment]
I know that mod_assign and mod_choice both have the option, and there's an ongoing epic at https://tracker.moodle.org/browse/MDL-35731.

**Comment by mchurchward** [comment]
While I think this might still be a useful change, the codebase has changed so much that this needs to be reworked. If you wish this to still be included, please redo the PR against the latest STABLE branch.

**Comment by tonyjbutler** [comment]
Just to be clear Mike, you'd like me to create a pull request against the MOODLE_38_STABLE branch rather than master?

**Comment by mchurchward** [comment]
Yes. Or wait a day and do it against the new MOODLE_39_STABLE branch (not yet created).

**Comment by tonyjbutler** [comment]
Here you go: https://github.com/PoetOS/moodle-mod_questionnaire/pull/297

**Pull request closed without merging**
