### PR TITLE
Save responses when required are missing on page breaks

### LINKED ISSUE #305: Responses are not stored when other required are missing
Hi @mchurchward 

We've encountered following problem. When you are building a questionnaire with page breaks, it will fail to show the `checked` state on the radio-buttons, as these value aren't stored in the `questionnaire_response_bool` or whatever table.

The error message is correct, and tells you, that you must answer the one reuired missing question, but the other correct answered responses aren't anymore checked on this view.

The same behaviour is, on the last page, when you want to submit a questionnaire.

So I think we need to add these missing functions to the `prev`, `next` and `submit` actions on the formdata.

Greets,
Adrian

### PR DESCRIPTION
**Pull request by adpe**
They will saved when the questionnaire has prev, next navigation buttons and when submitting the questionnaire on the last page.

Will resolve #305.

### CODE REVIEW

**Comment by adpe** [comment]
Hi @mchurchward 

Rebase done!

Cheers,
Adrian

**Comment by adpe** [comment]
Hi @mchurchward 

Thanks for your feedback. I'll have again a look. Thanks for the hint - you know your code better than me. ;-)

Greets,
Adrian

**Comment by mchurchward** [comment]
I think the "existing_response_action" would be the function to use. You should also check if this fix is needed for the mobile version.

**Comment by adpe** [comment]
Hi @mchurchward 

This line `response_insert` is already in this function, see https://github.com/PoetOS/moodle-mod_questionnaire/blob/master/questionnaire.class.php#L1041-L1051. The problem is that previous_page_action and next_page_action functions are not called when a requried field is missing, as the function `response_check_format` will return a true as there are missing questions.

Here's a snippet for the previos_page_action, see https://github.com/PoetOS/moodle-mod_questionnaire/blob/master/questionnaire.class.php#L1146-L1158. So actually what I can do is to replace my code with the `existing_response_action` function.

Please have a look at this issue carefully, so that you understand what is wrong.

HTH,
Adrian

**Comment by mchurchward** [comment]
Sorry for the back and forth. Your PR has fallen behind MOODLE_39_STABLE again. Can you rebase with MOODLE_39_STABLE once more? That should make the PR work properly.

**Comment by mchurchward** [comment]
I went ahead and rebased this myself. I'll close it now.

**Comment by adpe** [comment]
Was done in https://github.com/PoetOS/moodle-mod_questionnaire/commit/85b78eed8d9e076b8dabaf34943b5ade5fd15916.

Thank you very much!

**Pull request closed without merging**
