### PR TITLE
Add questionnairename field option in export CSV

### PR DESCRIPTION
**Pull request by adpe**

### CODE REVIEW

**Comment by adpe** [comment]
Hi @mchurchward 

I just see that https://github.com/adpe/moodle-mod_questionnaire/commit/013533a4f8a6a32b7401c6020dc468247298cfa3#diff-3a8270dae2b17999b935edc868c22cebR44 should be two lines above.

What do you think about this issue? Should I rework this and provide this new?

**Comment by adpe** [comment]
Hi @mchurchward 

That's not a mobile issue. It's just an enhancement of the existing `downloadoptions`.

**Comment by adpe** [comment]
Hi @mchurchward 

What do you think of this feature request? As you see there are three issues opened about this enhancement:
- https://github.com/PoetOS/moodle-mod_questionnaire/issues/153
- https://github.com/PoetOS/moodle-mod_questionnaire/issues/120

And this one. Thank you.

**Comment by mchurchward** [comment]
Sorry for the long delay on this...
I brought  this into MOODLE_37_STABLE, but it doesn't work unless the questionnaire is a "public" questionnaire. It looks like "questionnairename" needs to be set for private questionnaire (the most common). Can you take a look at and resubmit against MOODLE_37_STABLE?

**Comment by adpe** [comment]
I'll look to it until the end of this month. Thanks for your answers, apart from the delay.

**Comment by adpe** [comment]
As this will be done in https://github.com/PoetOS/moodle-mod_questionnaire/pull/259 I'll close it here.

**Pull request closed without merging**
